# Width and Height of the project window
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 720

# Helper button proportions and position on the screen
HELPER_BUTTON_WIDTH = 0.2 * WINDOW_WIDTH
HELPER_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
HELPER_BUTTON_X_POS = (WINDOW_WIDTH - HELPER_BUTTON_WIDTH) / 2
HELPER_BUTTON_Y_POS = 0.5 * WINDOW_HEIGHT

# Seeker button proportions and position on the screen
SEEKER_BUTTON_WIDTH = 0.2 * WINDOW_WIDTH
SEEKER_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
SEEKER_BUTTON_X_POS = (WINDOW_WIDTH - SEEKER_BUTTON_WIDTH) / 2
SEEKER_BUTTON_Y_POS = HELPER_BUTTON_Y_POS + HELPER_BUTTON_HEIGHT + 10

LINE_MAX_LENGTH = 20


BLACK = (0, 0, 0)
GREY = (50, 50, 50)
WHITE = (255, 255, 255)
LIGHT_GRAY = (134, 134, 134)
YELLOW = (245, 222, 105)
