# Width and Height of the project window
from pygame.examples.midi import BACKGROUNDCOLOR

WINDOW_WIDTH = 360
WINDOW_HEIGHT = 720

# Helper button proportions and position on the screen
HELPER_BUTTON_WIDTH = 0.3 * WINDOW_WIDTH
HELPER_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
HELPER_BUTTON_X_POS = (WINDOW_WIDTH - HELPER_BUTTON_WIDTH) / 2
HELPER_BUTTON_Y_POS = 0.5 * WINDOW_HEIGHT

# Seeker button proportions and position on the screen
SEEKER_BUTTON_WIDTH = 0.3 * WINDOW_WIDTH
SEEKER_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
SEEKER_BUTTON_X_POS = (WINDOW_WIDTH - SEEKER_BUTTON_WIDTH) / 2
SEEKER_BUTTON_Y_POS = HELPER_BUTTON_Y_POS + HELPER_BUTTON_HEIGHT + 10

# Go back button proportions and position on the screen
GO_BACK_BUTTON_WIDTH = 0.2 * WINDOW_WIDTH
GO_BACK_BUTTON_HEIGHT = 0.06 * WINDOW_HEIGHT
GO_BACK_BUTTON_X_POS = 0
GO_BACK_BUTTON_Y_POS = WINDOW_HEIGHT - GO_BACK_BUTTON_HEIGHT

# Name button proportions and position on the screen
NAME_BUTTON_WIDTH = 0.3 * WINDOW_WIDTH
NAME_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
NAME_BUTTON_X_POS = (WINDOW_WIDTH - NAME_BUTTON_WIDTH) / 5
NAME_BUTTON_Y_POS = 0.5 * WINDOW_HEIGHT

# City button proportions and position on the screen
CITY_BUTTON_WIDTH = 0.3 * WINDOW_WIDTH
CITY_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
CITY_BUTTON_X_POS = (WINDOW_WIDTH - CITY_BUTTON_WIDTH) / 5
CITY_BUTTON_Y_POS = NAME_BUTTON_Y_POS + NAME_BUTTON_HEIGHT + 10

# Next button proportions and position on the screen
NEXT_BUTTON_WIDTH = 0.3 * WINDOW_WIDTH
NEXT_BUTTON_HEIGHT = 0.08 * WINDOW_HEIGHT
NEXT_BUTTON_X_POS = (WINDOW_WIDTH - NEXT_BUTTON_WIDTH) / 2
NEXT_BUTTON_Y_POS = CITY_BUTTON_Y_POS + CITY_BUTTON_HEIGHT + 30

# Welcome text proportions and position on the screen
WELCOME_TEXT_Y_POS = 0.35 * WINDOW_HEIGHT

# Choose help text position on the screen
CHOOSE_HELP_TEXT_Y = 0.35 * WINDOW_HEIGHT

# Seek help buttons
SEEK_HELP_BUTTON_Y_POS = CHOOSE_HELP_TEXT_Y # start pos
SEEK_HELP_BUTTON_X_POS = 72
SEEK_HELP_BUTTON_WIDTH = 0.6 * WINDOW_WIDTH
SEEK_HELP_BUTTON_HEIGHT = 50


LINE_MAX_LENGTH = 20


BLACK = (0, 0, 0)
GREY = (50, 50, 50)
WHITE = (255, 255, 255)
LIGHT_GRAY = (134, 134, 134)
YELLOW = (245, 222, 105)
BACKGROUND_COLOR = (251, 200, 43)
